# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
import os
import urllib.request
import numpy as np


driver = webdriver.Chrome()

driver.get("http://s8.bitdl.ir/Series/Family.Guy/S01/")
# elements = driver.find_elements_by_class_name('thumb')
# table =  driver.find_element_by_xpath("//tbody")
myLinks =[]


print(type(myLinks))
for row in driver.find_elements_by_xpath(".//tr")[1:]:
    myLinks.append([td.get_attribute("href") for td in row.find_elements_by_xpath(".//td/a")])

my_array = np.array(myLinks)
print(my_array[1:])
print(type(my_array))

# myLinks=driver.find_elements_by_xpath("//div[@class='thumb']/a")
for index,link in enumerate(my_array[1:],1):
    print(index)
    urllib.request.urlretrieve(link, 'video_name.mkv')

driver.close()


    